version: '3.7'
services:
  web:
    build: .
    container_name: dbdbwls_web
    ports:
      - "5000:5000"
    links: 
      - redis:db
  redis:
    image: "redis:alpine"
    container_name: dbdbwls_db